### PR TITLE
Underdetermined constraints with zero not being a solution

### LINKED ISSUE #322: Witness generation should fail if there are "incomplete" identities
Currently, witness generation just continues with "unknown" values if no new values can be derived (the identity returns "incomplete").

In practice, these unknowns are set to zero.

We should at least check if setting all unknowns to zero will make the identities fail or not. This can be a new return code: Incomplete, but OK with just setting unknows to zero, or incomplete, but just setting them to zero does not work.

Maybe this is just the distinction between "don't care" and "don't know".

### PR DESCRIPTION
**Pull request by chriseth**
Fixes #322

Depends on https://github.com/powdr-org/powdr/pull/325, otherwise ready

### CODE REVIEW

**Comment by leonardoalt** [comment]
Tests are failing

File: compiler/tests/pil.rs [hunk 1]
```diff
@@ -61,6 +61,12 @@ fn test_witness_lookup() {
     );
 }
 
+#[test]
+#[should_panic]
```
Comment (lvella) [inline compiler/tests/pil.rs:65]: Using `#[should_panic]` will further the issue #312, i.e. we don't know if the thing failed where it was supposed to fail. That said, we would need a major refactor to make `verify_pil()` return error, so maybe leave as is or use `std::panic::catch_unwind()` and assert against the error message.

File: compiler/tests/pil.rs [hunk 2]
```diff
@@ -61,6 +61,12 @@ fn test_witness_lookup() {
...
+fn test_underdetermined_zero_no_solution() {
+    verify_pil("underdetermined_zero_no_solution.pil", None);
```
Comment (lvella) [inline compiler/tests/pil.rs:67]: Using `#[should_panic]` will further the issue #312, i.e. we don't know if the thing failed where it was supposed to fail. That said, we would need a major refactor to make `verify_pil()` return an error, so maybe leave as is or use `std::panic::catch_unwind()` and assert against the error message?

File: executor/src/witgen/generator.rs [hunk 3]
```diff
@@ -106,27 +125,26 @@ where
...
-                        progress |= self.handle_eval_result(result);
+                        progress |= self.handle_eval_result(result, strategy);
                     }
                 }
             }
 
-            if !progress {
-                break;
-            }
-            if self.next.iter().all(|v| v.is_some()) {
```
Comment (lvella) [inline executor/src/witgen/generator.rs:128]: It seems like this exit condition (when all v are set) is missing in the new code.

File: executor/src/witgen/generator.rs [hunk 4]
```diff
@@ -418,10 +464,14 @@ where
...
     /// Returns true if a new value or constraint was determined.
-    fn handle_eval_result(&mut self, result: EvalResult<T>) -> bool {
+    fn handle_eval_result(&mut self, result: EvalResult<T>, strategy: SolvingStrategy) -> bool {
         match result {
             Ok(constraints) => {
                 let progress = !constraints.is_empty();
+                // If we assume unknown variables to be zero, we cannot learn anything new.
+                if strategy == SolvingStrategy::AssumeZero {
+                    assert!(!progress);
+                }
```
Comment (lvella) [inline executor/src/witgen/generator.rs:474]: Much less readable one-liner version that I would have used:
```
assert!(strategy != SolvingStrategy::AssumeZero || !progress);
```
or maybe even
```
assert!(!(strategy == SolvingStrategy::AssumeZero && progress));
```
Glad you didn't!

File: executor/src/witgen/generator.rs [hunk 5]
```diff
@@ -41,6 +41,22 @@ enum EvaluationRow {
     Next,
 }
 
+#[derive(PartialEq, Eq, Clone, Copy)]
+enum SolvingStrategy {
+    /// Only solve expressions that are affine in a single variable
+    /// (and use bit constraints).
+    SingleVariableAffine,
+    /// Assume that all unknown values are zero and check that this does not generate
+    /// a conflict (but do not store the values as fixed zero to avoid relying on nondeterminism).
```
Comment (lvella) [inline executor/src/witgen/generator.rs:50]: Regarding this comment, any kind of more complex solver we add would have to rely on nondeterminism, no?

Like, a solver that only looks at one div equation `divisor * QUOT + REM = dividend` would have a whole 1-D curve of solutions.

Comment (chriseth) [reply executor/src/witgen/generator.rs:50]: yes of course. but if we are lucky, there might be bit constraints. I didn't analyze the problem fully yet, it could be that bit constraints do not always rule out other solutions to the individual div equation.

I mean in the end of course it should not need to rely on nondeterminism, but it might be difficult to check.

File: executor/src/witgen/generator.rs (hunk 3 above)
Comment (chriseth) [reply executor/src/witgen/generator.rs:128]: Yes, this is intentional to add further checks.

**Review by lvella — APPROVED** [review]
